name: Go-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.1
      - name: Install Compilers
        run: |
          sudo apt-get update
          sudo apt-get install --yes build-essential pkgconf libelf-dev llvm clang linux-tools-common linux-tools-generic
          go get -u github.com/shuLhan/go-bindata/...
        shell: bash
      - name: Network Interface
        run: |
          ip -4 route show
          ip -o -4 route show to default
      - name: Test
        run: |
          go test -exec sudo ./...
          cd examples/
          sh test.sh
